#fname= ["susan", "fola", "feyi", "bola", "john", "dayo"]




#  fname = input("enter your username : ")
# match fname : 
#     case "susan":
#          print (f"this is {fname}")
#     case "fola" :
#         print (f"this is {fname}")
#     case "feyi":
#         print (f"this is solomon")
#     case "bola":
#         print : (f"this is {fname}")
#     case "john":
#         print : (f"this is {fname}")

        





# studentprofile = [
#                     {   "name" : "john",
#                         "age" : "12",
#                         "class" : [ "web Dev" , "devops", "data analytics"]
#                     },
#                     {    "name" : "bola" ,
#                         "age" : "23" ,
#                         "class": [ "web Dev" , "devops", "data analytics"]
#                     },
#                     {
#                         "name": "seyi" ,
#                         "age" : "32" ,
#                         "class": ["web Dev", "devops", "data analytics"]
#                     },
#                     {
#                         "name": "solomon",
#                          "age": "43",
#                          "course": ["web dev", "devops", "data analytics"]
#                     },
#                     {
#                         "name": "dayo",
#                         "age": "49",
#                         "course": ["web dev", "devops", "data analytics"]
#                     }
#                 ]
# print(studentprofile[3]["name"])
# print(studentprofile[3]["age"])
# print(studentprofile[3]["course"])

# print(f"my name is {studentprofile [3]['name']} and i study  {studentprofile [3]['course']}, i am  {studentprofile [3]['age']}")



# num = int(input ("enter a digit:"))
# if(num%2 == 0):
#     print(f"this even number : {num}")
# else :
#     print(f"this is odd or prime numbers")



# students = ["temi" , "solomon", "ade", "bisi"]
# if(students[2] == "tope"):
#     print("tope is present")
# else:
#     students[2]="tope"
#     print ("tope is absent")




def greetuser():
    pass




    # function call
    greetuser()